create or replace view glioma__valueset_casedef as select * from (values
('http://snomed.info/sct', '100731000119107', 'Low grade astrocytoma of brain')
,('http://snomed.info/sct', '128854008', 'Juvenile astrocytoma')
,('http://snomed.info/sct', '254976006', 'Optic nerve glioma')
,('http://snomed.info/sct', '277507004', 'Pilocytic astrocytoma of cerebellum')
,('http://snomed.info/sct', '416351002', 'Intraocular glioma')
,('http://snomed.info/sct', '428960009', 'Low grade glioma of brainstem')
,('http://snomed.info/sct', '428964000', 'Low grade glioma of cerebrum')
,('http://snomed.info/sct', '428965004', 'Low grade glioma of thalamus')
,('http://snomed.info/sct', '429408002', 'Low grade glioma of brain')
,('http://snomed.info/sct', '763865009', 'Pilocytic astrocytoma')
,('http://snomed.info/sct', '780822000', 'Desmoplastic infantile astrocytoma and ganglioglioma')
,('http://snomed.info/sct', '87191000119100', 'Ganglioglioma')
,('http://snomed.info/sct', '1157060001', 'Diffuse astrocytoma')
,('http://snomed.info/sct', '189924002', 'Pleomorphic xanthoastrocytoma')
,('http://snomed.info/sct', '449799008', 'Subependymal giant cell astrocytoma')
,('http://snomed.info/sct', '87211000119104', 'Dysembryoplastic neuroepithelial tumor')
,('http://snomed.info/sct', '724807008', 'Glioma of central nervous system')
,('http://snomed.info/sct', '715900001', 'Chordoid glioma')
,('http://snomed.info/sct', '733123006', 'Diffuse leptomeningeal glioneuronal neoplasm')
,('http://snomed.info/sct', '428954009', 'Low grade glioma')
,('http://snomed.info/sct', '414950005', 'Optic nerve glioma of orbit')
,('http://snomed.info/sct', '417619001', 'Intracranial optic nerve glioma')
,('http://snomed.info/sct', '428753007', 'Low grade glioma of cerebellum')
,('http://snomed.info/sct', '4553004', 'Subependymal glioma')
,('http://snomed.info/sct', '89880005', 'Ganglioglioma')
,('http://snomed.info/sct', '424151006', 'Anaplastic glioma of brain')
,('http://snomed.info/sct', '450900009', 'Angiocentric glioma')
,('http://snomed.info/sct', '90811000119100', 'Low grade malignant glioma of brain')
,('http://snomed.info/sct', '1157070004', 'Pilomyxoid astrocytoma')
,('http://snomed.info/sct', '1196902006', 'Angiocentric glioma of brain')
,('http://snomed.info/sct', '443937008', 'Mixed glioma')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C71', 'Malignant neoplasm of brain')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C71.0', 'Malignant neoplasm of supratentorial NOS')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C71.1', 'Malignant neoplasm of frontal lobe')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C71.2', 'Malignant neoplasm of temporal lobe')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C71.3', 'Malignant neoplasm of parietal lobe')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C71.4', 'Malignant neoplasm of occipital lobe')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C71.5', 'Malignant neoplasm of cerebral ventricle')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C71.6', 'Malignant neoplasm of cerebellum')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C71.7', 'Malignant neoplasm of brain stem')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C71.8', 'Malignant neoplasm of overlapping sites of brain')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C71.9', 'Malignant neoplasm of brain, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C72.3', 'Malignant neoplasm of optic nerve')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C72.30', 'Malignant neoplasm of unspecified optic nerve')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C72.31', 'Malignant neoplasm of right optic nerve')
,('http://hl7.org/fhir/sid/icd-10-cm', 'C72.32', 'Malignant neoplasm of left optic nerve')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D33.0', 'Benign neoplasm of brain, supratentorial')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D33.1', 'Benign neoplasm of brain, infratentorial')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D33.2', 'Benign neoplasm of brain, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D33.3', 'Benign neoplasm of cranial nerves')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D33.4', 'Benign neoplasm of spinal cord')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D33.9', 'Benign neoplasm of central nervous system, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D43.0', 'Neoplasm of uncertain behavior of brain, supratentorial')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D43.1', 'Neoplasm of uncertain behavior of brain, infratentorial')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D43.2', 'Neoplasm of uncertain behavior of brain, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D43.3', 'Neoplasm of uncertain behavior of cranial nerves')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D43.4', 'Neoplasm of uncertain behavior of spinal cord')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D43.8', 'Neoplasm of uncertain behavior of other specified parts of central nervous system')
,('http://hl7.org/fhir/sid/icd-10-cm', 'D43.9', 'Neoplasm of uncertain behavior of central nervous system, unspecified')
,('http://hl7.org/fhir/sid/icd-9-cm', '191', 'Malignant neoplasm of brain')
,('http://hl7.org/fhir/sid/icd-9-cm', '191.0', 'Malignant neoplasm of cerebrum, except lobes and ventricles')
,('http://hl7.org/fhir/sid/icd-9-cm', '191.1', 'Malignant neoplasm of frontal lobe')
,('http://hl7.org/fhir/sid/icd-9-cm', '191.2', 'Malignant neoplasm of temporal lobe')
,('http://hl7.org/fhir/sid/icd-9-cm', '191.3', 'Malignant neoplasm of parietal lobe')
,('http://hl7.org/fhir/sid/icd-9-cm', '191.4', 'Malignant neoplasm of occipital lobe')
,('http://hl7.org/fhir/sid/icd-9-cm', '191.5', 'Malignant neoplasm of ventricles')
,('http://hl7.org/fhir/sid/icd-9-cm', '191.6', 'Malignant neoplasm of cerebellum nos')
,('http://hl7.org/fhir/sid/icd-9-cm', '191.7', 'Malignant neoplasm of brain stem')
,('http://hl7.org/fhir/sid/icd-9-cm', '191.8', 'Malignant neoplasm of other parts of brain')
,('http://hl7.org/fhir/sid/icd-9-cm', '191.9', 'Malignant neoplasm of brain, unspecified')
,('http://hl7.org/fhir/sid/icd-9-cm', '225.0', 'Benign neoplasm of brain')
,('http://hl7.org/fhir/sid/icd-9-cm', '225.1', 'Benign neoplasm of cranial nerves')
,('http://hl7.org/fhir/sid/icd-9-cm', '225.2', 'Benign neoplasm of cerebral meninges')
,('http://hl7.org/fhir/sid/icd-9-cm', '225.3', 'Benign neoplasm of spinal cord')
,('http://hl7.org/fhir/sid/icd-9-cm', '225.4', ' Benign neoplasm of spinal meninges"')
,('http://hl7.org/fhir/sid/icd-9-cm', '225.8', 'Benign neoplasm of other specified sites of nervous system')
,('http://hl7.org/fhir/sid/icd-9-cm', '225.9', 'Benign neoplasm of nervous system, part unspecified')
,('http://hl7.org/fhir/sid/icd-9-cm', '237.5', 'Neoplasm of uncertain behavior of brain and spinal cord')
) AS t (system, code, display) ;